version: '2'
services:
  comments_bd:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "4303:27017"
  comments_ms:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3303 -b '0.0.0.0'"
    ports:
      - "3303:3303"
    links:
      - comments_bd
