version: '2'
services:
  comments_bd:
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  comments_ms:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    links:
      - comments_bd
